### ISSUE TITLE
Time complexity

### ISSUE THREAD

**Issue by KeyBoarder8** [familyld/DeepCF#1]
The code stays in the initial result and can't run down.

**Comment by familyld** [comment]
Hi, @KeyBoarder8 
First, the provided models are well trained and they should show the same result as presented in the paper. To further fine-tuning the model, you need to tune the parameters carefully.
Second, to see the improvement of DeepCF, you can train DMF and MLP from scratch and then fine-tuning CFNet.
Thanks for your attention.
