### ISSUE TITLE
DMF and MLP are not right?

### ISSUE THREAD

**Issue by panyx0718** [familyld/DeepCF#2]
https://github.com/familyld/DeepCF/blob/16f1569059783eac21e46d9fabf86ad60ea1ceb8/CFNet.py#L81

According to the paper, MLP doesn't involve the concat operation and DMF does?

**Comment by familyld** [comment]
Hi, @panyx0718. Thank you for your attention. According to Figure 2, MLP is on the right hand side while DMF is on the left hand side. MLP need to concatenate the user embedding vector and item embedding vector before passing them to the subsequent layers.

**Comment by panyx0718** [comment]
I see, thanks. I thought the right side is DMF (Deep Matching Function)...
