### ISSUE TITLE
error：cannot create a tensor proto whose content is larger than 2GB

### ISSUE THREAD

**Issue by sunshinelium** [familyld/DeepCF#3]
test pinterest dataset ，raise cannot create a tensor proto whose content is larger than 2GB，do you have some idea on this error? thanks

**Comment by familyld** [comment]
As Tensorflow doesn't support tensors larger than 2GB, you can turn to other frameworks such as pytorch. In addition, you can also try to input ids instead of the full rating matrix (which requires large memory) although ids are less informative than multi-hot ratings.

**Comment by sunshinelium** [comment]
thanks for you reply, i will try it
