### ISSUE TITLE
How to preprocess the datasets?

### ISSUE THREAD

**Issue by SyedTauhidUllahShah** [familyld/DeepCF#6]
How to process the datasets? I mean, how to construct the negative, test and rating files from a dataset.

**Comment by familyld** [comment]
As given in the paper, The ml-1m dataset has been preprocessed by the provider (NeuMF (He et al. 2017)). Each user has at least 20 ratings and each item has been rated by at least 5 users. We process the other three datasets in the same way.

You can also see the format of the negative, test and rating files in the README.md. Feel free to create your own datasets.

**Comment by SyedTauhidUllahShah** [comment]
Thank you so much for your kind response. But actually I need the code to
process the datasets. I mean how can I split a dataset into the test, train
and negatives. If you can plz provide me the code to process a new dataset.

**Comment by familyld** [comment]
@tauhidshah You can and you definitely should write your own code for new datasets since the raw data can be very different for different data sets. The coding is not difficult and you may find the pandas library is useful.
